### ISSUE TITLE
Provide web application

### ISSUE THREAD

**Issue by lavaoutsiders** [MathijsHubrechtsen/DRAMA-Compiler#3]
Provide a Java servlet application

Including:

- [ ] Deploy the webserver with TomCat, Apache etc.
- [ ] Make Webpages (Using MVC Frameworks)
- [ ] Testing and deploy and test the website/ webserver

**Comment by Frostielocks** [comment]
I'm going to close this issue because in my opinion deploying the DRAMA-Compiler on a web server is not necessary. The time investment required to make this work is in my opinion simply not worth the marginal benefit of having a small scale compiler web application. However, after the project is finished, I am certainly open to deploying a website where users can install the compiler and read documentation.
